"""Core interface labels in the six official languages of the UN."""

LANGUAGES = {
    "English": "en",
    "العربية": "ar",
    "中文": "zh",
    "Français": "fr",
    "Русский": "ru",
    "Español": "es",
}

TEXT = {
    "en": {
        "nav": "Explore", "map": "Field map", "planner": "Planting plan", "doctor": "Plant doctor",
        "history": "My history", "impact": "Impact & policies", "share": "Share app", "account": "Account",
        "language": "Language", "offline": "Offline mode", "tagline": "A practical guide to healthier, more productive fields",
        "problem": "Good land decisions should not depend on guesswork or an expensive plant doctor.",
        "map_title": "Understand your field", "map_intro": "Choose a point to review climate and soil signals, then compare crops against transparent ranges.",
        "planner_title": "Plan crops to grow together", "planner_intro": "Explore locally screened companion crops and see why each pairing may fit.",
        "doctor_title": "Check a leaf", "doctor_intro": "Take or upload a clear leaf photo for a first-pass disease screening and practical next steps.",
        "history_title": "Your saved field history", "history_intro": "Review your past suitability checks and plant health screenings.",
        "impact_title": "Project goals and policies", "sdg_title": "Relevant UN Sustainable Development Goals",
        "privacy_title": "Privacy policy", "terms_title": "Terms of use", "share_title": "Open CropWise on another device",
        "username": "Username", "password": "Password", "sign_in": "Sign in", "register": "Create account", "logout": "Sign out",
        "guest": "Continue as guest", "analyze": "Analyze field", "find_crops": "Find suitable crops", "analyze_leaf": "Screen this leaf",
        "upload": "Upload a leaf photo", "temperature": "Average temperature", "rainfall": "Annual rainfall", "soil_ph": "Soil pH",
        "select_crop": "Choose a main crop", "offline_note": "Offline mode uses saved local data or values you enter. First-time setup and live data refresh need internet.",
        "online_note": "Live climate and soil lookups use free public services and need an internet connection.",
        "no_history": "No saved activity yet. Sign in to save future checks on this installation.",
        "screening_warning": "This is an early screening aid, not a diagnosis or yield guarantee. Confirm important decisions with local agricultural guidance.",
        "qr_missing": "Set the public app URL in APP_PUBLIC_URL to create a QR code that opens this deployment.",
        "treatment_title": "Low-cost first steps", "language_note": "Core navigation and guidance are available in six UN languages; crop names and some source data remain in their published language.",
        "public_url": "Public app URL", "download_qr": "Download QR code", "scan_qr": "Scan this code to open CropWise", "camera_photo": "Take a leaf photo",
    },
    "ar": {
        "nav": "استكشف", "map": "خريطة الحقل", "planner": "خطة الزراعة", "doctor": "طبيب النبات",
        "history": "سجلي", "impact": "الأثر والسياسات", "share": "مشاركة التطبيق", "account": "الحساب",
        "language": "اللغة", "offline": "وضع عدم الاتصال", "tagline": "دليل عملي لحقول أكثر صحة وإنتاجية",
        "problem": "ينبغي ألا تعتمد قرارات استخدام الأرض على التخمين أو على طبيب نبات مكلف.",
        "map_title": "افهم حقلك", "map_intro": "اختر موقعاً لمراجعة مؤشرات المناخ والتربة، ثم قارن المحاصيل بنطاقات واضحة.",
        "planner_title": "خطط للمحاصيل التي تنمو معاً", "planner_intro": "استكشف محاصيل مصاحبة مناسبة مبدئياً للموقع واعرف سبب كل اقتراح.",
        "doctor_title": "افحص ورقة نبات", "doctor_intro": "التقط صورة واضحة أو ارفعها للحصول على فحص أولي وإرشادات عملية.",
        "history_title": "سجل الحقول المحفوظ", "history_intro": "راجع فحوص الملاءمة السابقة وفحوص صحة النباتات.",
        "impact_title": "أهداف المشروع والسياسات", "sdg_title": "أهداف الأمم المتحدة للتنمية المستدامة ذات الصلة",
        "privacy_title": "سياسة الخصوصية", "terms_title": "شروط الاستخدام", "share_title": "افتح CropWise على جهاز آخر",
        "username": "اسم المستخدم", "password": "كلمة المرور", "sign_in": "تسجيل الدخول", "register": "إنشاء حساب", "logout": "تسجيل الخروج",
        "guest": "المتابعة كضيف", "analyze": "حلل الحقل", "find_crops": "اعثر على محاصيل مناسبة", "analyze_leaf": "افحص هذه الورقة",
        "upload": "ارفع صورة ورقة نبات", "temperature": "متوسط الحرارة", "rainfall": "الأمطار السنوية", "soil_ph": "درجة حموضة التربة",
        "select_crop": "اختر المحصول الرئيسي", "offline_note": "يستخدم وضع عدم الاتصال البيانات المحلية المحفوظة أو القيم التي تدخلها. يحتاج الإعداد الأولي وتحديث البيانات المباشرة إلى الإنترنت.",
        "online_note": "تستخدم بيانات المناخ والتربة المباشرة خدمات عامة مجانية وتتطلب اتصالاً بالإنترنت.",
        "no_history": "لا يوجد نشاط محفوظ بعد. سجّل الدخول لحفظ الفحوص المستقبلية على هذا التثبيت.",
        "screening_warning": "هذه أداة فحص أولي وليست تشخيصاً أو ضماناً للمحصول. استشر الإرشاد الزراعي المحلي للقرارات المهمة.",
        "qr_missing": "أضف رابط التطبيق العام في APP_PUBLIC_URL لإنشاء رمز يفتح هذا النشر.",
        "treatment_title": "خطوات أولية منخفضة التكلفة", "language_note": "التنقل والإرشادات الأساسية متاحة بست لغات أممية؛ تبقى أسماء المحاصيل وبعض البيانات بلغتها المنشورة.",
        "public_url": "رابط التطبيق العام", "download_qr": "تنزيل رمز الاستجابة السريعة", "scan_qr": "امسح الرمز لفتح CropWise", "camera_photo": "التقط صورة للورقة",
    },
    "zh": {
        "nav": "功能", "map": "田地地图", "planner": "种植计划", "doctor": "植物医生",
        "history": "使用记录", "impact": "影响与政策", "share": "分享应用", "account": "账户",
        "language": "语言", "offline": "离线模式", "tagline": "帮助农田更健康、更高效的实用指南",
        "problem": "土地决策不应依赖猜测，也不应必须求助昂贵的植物医生。",
        "map_title": "了解您的田地", "map_intro": "选择位置查看气候和土壤指标，再根据透明的范围比较作物。",
        "planner_title": "规划适合共同种植的作物", "planner_intro": "查看适合该地点的伴生作物建议及其原因。",
        "doctor_title": "检查叶片", "doctor_intro": "上传清晰的叶片照片，进行初步病害筛查并获取实用建议。",
        "history_title": "已保存的田地记录", "history_intro": "查看以前的适宜性分析和植物健康筛查。",
        "impact_title": "项目目标与政策", "sdg_title": "相关联合国可持续发展目标",
        "privacy_title": "隐私政策", "terms_title": "使用条款", "share_title": "在其他设备上打开 CropWise",
        "username": "用户名", "password": "密码", "sign_in": "登录", "register": "创建账户", "logout": "退出登录",
        "guest": "以访客身份继续", "analyze": "分析田地", "find_crops": "查找适宜作物", "analyze_leaf": "筛查此叶片",
        "upload": "上传叶片照片", "temperature": "平均气温", "rainfall": "年降雨量", "soil_ph": "土壤酸碱度",
        "select_crop": "选择主要作物", "offline_note": "离线模式使用本地保存的数据或您输入的数值。首次设置和实时数据更新需要互联网。",
        "online_note": "实时气候和土壤数据来自免费的公共服务，需要互联网连接。", "no_history": "暂无保存记录。登录后可在此安装中保存后续检查。",
        "screening_warning": "此工具仅用于初步筛查，不构成诊断或产量保证。重要决策请咨询当地农业指导机构。",
        "qr_missing": "请在 APP_PUBLIC_URL 中设置公开应用网址，以生成可打开此部署的二维码。",
        "treatment_title": "低成本初步措施", "language_note": "核心导航与指南支持联合国六种官方语言；作物名称和部分来源数据保留其发布语言。",
        "public_url": "应用公开网址", "download_qr": "下载二维码", "scan_qr": "扫描此码以打开 CropWise", "camera_photo": "拍摄叶片照片",
    },
    "fr": {
        "nav": "Explorer", "map": "Carte du champ", "planner": "Plan de plantation", "doctor": "Santé des plantes",
        "history": "Mon historique", "impact": "Impact et politiques", "share": "Partager l’application", "account": "Compte",
        "language": "Langue", "offline": "Mode hors ligne", "tagline": "Un guide pratique pour des champs plus sains et productifs",
        "problem": "Les décisions foncières ne devraient pas dépendre du hasard ou d’un spécialiste coûteux.",
        "map_title": "Comprendre votre champ", "map_intro": "Choisissez un point pour consulter le climat et le sol, puis comparez les cultures selon des seuils transparents.",
        "planner_title": "Planifier des cultures associées", "planner_intro": "Découvrez des associations adaptées au site et les raisons de chaque suggestion.",
        "doctor_title": "Examiner une feuille", "doctor_intro": "Importez une photo nette pour un premier dépistage et des conseils pratiques.",
        "history_title": "Historique de vos champs", "history_intro": "Consultez vos analyses de culture et dépistages précédents.",
        "impact_title": "Objectifs et politiques du projet", "sdg_title": "Objectifs de développement durable concernés",
        "privacy_title": "Politique de confidentialité", "terms_title": "Conditions d’utilisation", "share_title": "Ouvrir CropWise sur un autre appareil",
        "username": "Nom d’utilisateur", "password": "Mot de passe", "sign_in": "Connexion", "register": "Créer un compte", "logout": "Déconnexion",
        "guest": "Continuer comme invité", "analyze": "Analyser le champ", "find_crops": "Trouver des cultures adaptées", "analyze_leaf": "Examiner cette feuille",
        "upload": "Importer une photo de feuille", "temperature": "Température moyenne", "rainfall": "Pluviométrie annuelle", "soil_ph": "pH du sol",
        "select_crop": "Choisir une culture principale", "offline_note": "Le mode hors ligne utilise les données locales ou les valeurs saisies. La première installation et l’actualisation des données nécessitent Internet.",
        "online_note": "Les données climatiques et pédologiques en direct proviennent de services publics gratuits et nécessitent Internet.",
        "no_history": "Aucune activité enregistrée. Connectez-vous pour enregistrer les prochains contrôles sur cette installation.",
        "screening_warning": "Cet outil fournit un premier dépistage, pas un diagnostic ni une garantie de rendement. Demandez conseil aux services agricoles locaux pour les décisions importantes.",
        "qr_missing": "Définissez l’URL publique dans APP_PUBLIC_URL pour créer un QR code ouvrant ce déploiement.",
        "treatment_title": "Premiers gestes à faible coût", "language_note": "La navigation et les conseils principaux sont disponibles dans les six langues officielles de l’ONU; les noms de cultures et certaines données gardent leur langue source.",
        "public_url": "URL publique de l’application", "download_qr": "Télécharger le QR code", "scan_qr": "Scannez ce code pour ouvrir CropWise", "camera_photo": "Prendre une photo de feuille",
    },
    "ru": {
        "nav": "Разделы", "map": "Карта поля", "planner": "План посадок", "doctor": "Помощник по растениям",
        "history": "История", "impact": "Влияние и правила", "share": "Поделиться приложением", "account": "Учётная запись",
        "language": "Язык", "offline": "Автономный режим", "tagline": "Практический помощник для здоровых и продуктивных полей",
        "problem": "Решения об использовании земли не должны зависеть от догадок или дорогого специалиста.",
        "map_title": "Изучите своё поле", "map_intro": "Выберите точку, чтобы посмотреть климат и почву, затем сравните культуры по понятным диапазонам.",
        "planner_title": "План совместных посадок", "planner_intro": "Посмотрите на подходящие для участка культуры-компаньоны и причины рекомендации.",
        "doctor_title": "Проверка листа", "doctor_intro": "Загрузите чёткое фото листа для первичной оценки болезни и практических советов.",
        "history_title": "История поля", "history_intro": "Просмотрите предыдущие оценки пригодности и проверки здоровья растений.",
        "impact_title": "Цели проекта и правила", "sdg_title": "Связанные Цели устойчивого развития ООН",
        "privacy_title": "Политика конфиденциальности", "terms_title": "Условия использования", "share_title": "Откройте CropWise на другом устройстве",
        "username": "Имя пользователя", "password": "Пароль", "sign_in": "Войти", "register": "Создать аккаунт", "logout": "Выйти",
        "guest": "Продолжить как гость", "analyze": "Анализ поля", "find_crops": "Подобрать культуры", "analyze_leaf": "Проверить лист",
        "upload": "Загрузить фото листа", "temperature": "Средняя температура", "rainfall": "Годовые осадки", "soil_ph": "Кислотность почвы",
        "select_crop": "Выберите основную культуру", "offline_note": "Автономный режим использует сохранённые локальные данные или введённые вами значения. Первичная настройка и обновление данных требуют интернета.",
        "online_note": "Актуальные климатические и почвенные данные поступают из бесплатных открытых сервисов и требуют подключения к интернету.",
        "no_history": "Сохранённых действий пока нет. Войдите, чтобы сохранять будущие проверки в этой установке.",
        "screening_warning": "Это предварительная оценка, а не диагноз и не гарантия урожая. Важные решения обсудите с местной аграрной службой.",
        "qr_missing": "Укажите общедоступный адрес приложения в APP_PUBLIC_URL, чтобы создать QR-код для этой версии.",
        "treatment_title": "Недорогие первые меры", "language_note": "Основная навигация и рекомендации доступны на шести официальных языках ООН; названия культур и часть исходных данных сохраняют язык публикации.",
        "public_url": "Общедоступный адрес приложения", "download_qr": "Скачать QR-код", "scan_qr": "Отсканируйте код, чтобы открыть CropWise", "camera_photo": "Сфотографировать лист",
    },
    "es": {
        "nav": "Explorar", "map": "Mapa del campo", "planner": "Plan de siembra", "doctor": "Salud de las plantas",
        "history": "Mi historial", "impact": "Impacto y políticas", "share": "Compartir la aplicación", "account": "Cuenta",
        "language": "Idioma", "offline": "Modo sin conexión", "tagline": "Una guía práctica para campos más sanos y productivos",
        "problem": "Las decisiones sobre la tierra no deberían depender de conjeturas ni de un especialista costoso.",
        "map_title": "Conoce tu campo", "map_intro": "Elige un punto para consultar el clima y el suelo; compara cultivos con rangos transparentes.",
        "planner_title": "Planifica cultivos asociados", "planner_intro": "Explora cultivos compañeros adecuados para el sitio y conoce por qué se sugieren.",
        "doctor_title": "Revisa una hoja", "doctor_intro": "Sube una foto clara para obtener una detección inicial y pasos prácticos.",
        "history_title": "Historial de tu campo", "history_intro": "Consulta tus evaluaciones de cultivo y revisiones de salud anteriores.",
        "impact_title": "Objetivos y políticas del proyecto", "sdg_title": "Objetivos de Desarrollo Sostenible relacionados",
        "privacy_title": "Política de privacidad", "terms_title": "Términos de uso", "share_title": "Abre CropWise en otro dispositivo",
        "username": "Nombre de usuario", "password": "Contraseña", "sign_in": "Iniciar sesión", "register": "Crear cuenta", "logout": "Cerrar sesión",
        "guest": "Continuar como invitado", "analyze": "Analizar campo", "find_crops": "Buscar cultivos adecuados", "analyze_leaf": "Revisar esta hoja",
        "upload": "Subir una foto de hoja", "temperature": "Temperatura media", "rainfall": "Lluvia anual", "soil_ph": "pH del suelo",
        "select_crop": "Elige un cultivo principal", "offline_note": "El modo sin conexión usa datos locales guardados o valores que introduces. La configuración inicial y las actualizaciones requieren internet.",
        "online_note": "Las consultas climáticas y del suelo usan servicios públicos gratuitos y requieren conexión a internet.",
        "no_history": "Todavía no hay actividad guardada. Inicia sesión para guardar futuras consultas en esta instalación.",
        "screening_warning": "Es una herramienta de detección inicial, no un diagnóstico ni una garantía de rendimiento. Consulta asesoría agrícola local para decisiones importantes.",
        "qr_missing": "Configura la URL pública en APP_PUBLIC_URL para crear un código QR que abra esta instalación.",
        "treatment_title": "Primeros pasos de bajo costo", "language_note": "La navegación y la guía principal están disponibles en los seis idiomas oficiales de la ONU; algunos nombres de cultivos y datos conservan su idioma original.",
        "public_url": "URL pública de la aplicación", "download_qr": "Descargar código QR", "scan_qr": "Escanea este código para abrir CropWise", "camera_photo": "Tomar una foto de la hoja",
    },
}

EXTRA_TEXT = {
    "en": {
        "privacy_body": "Draft for project review. The browser asks permission to read your device location for the map; you can deny it. Field coordinates go to NASA POWER, SoilGrids/ISRIC, and Open-Meteo only when online checks are run; map tile requests go to OpenStreetMap. Google sign-in shares your identity claims with the app, which uses a generated account ID to link saved activity. A leaf photo uploaded to a hosted app reaches the app server for inference and is not saved to the app database. The local SQLite database stores account IDs, local password hashes, saved checks, and cached field values. Hosted deployments need persistent, access-controlled storage.",
        "terms_body": "Draft for project review. Crop ranges, companion suggestions, and image predictions are general screening aids. They are not professional diagnosis, treatment instructions, or yield forecasts. Confirm important decisions with local agricultural guidance and check applicable rules before applying treatments. The user remains responsible for field decisions.",
        "sdg_note": "These are intended areas of contribution, not an official UN endorsement or measured impact claim.",
        "offline_detail": "The app uses free public datasets and open-source libraries without paid API keys. Saved point data and manually entered values can be used offline. Live map tiles and climate, soil, and elevation refreshes need internet. Download the disease model once before offline screening. A disconnected first-time setup requires preloading the model and field data.",
    },
    "ar": {
        "privacy_body": "مسودة لمراجعة المشروع. يطلب المتصفح الإذن لاستخدام موقع جهازك على الخريطة ويمكنك الرفض. تُرسل إحداثيات الحقل إلى NASA POWER وSoilGrids/ISRIC وOpen-Meteo عند إجراء الفحوص المباشرة فقط، وتُرسل طلبات الخرائط إلى OpenStreetMap. يرسل تسجيل الدخول عبر Google بيانات الهوية إلى التطبيق، الذي يستخدم معرّف حساب مُنشأ لربط النشاط المحفوظ. تصل صورة الورقة في التطبيق المستضاف إلى خادم التحليل ولا تُحفظ في قاعدة البيانات. تخزن SQLite معرّفات الحسابات وكلمات المرور المحلية المحمية والفحوص والقيم المؤقتة. يحتاج النشر المستضاف إلى تخزين دائم ومقيد الوصول.",
        "terms_body": "مسودة لمراجعة المشروع. نطاقات المحاصيل واقتراحات الزراعة المصاحبة وتنبؤات الصور أدوات فحص عامة، وليست تشخيصاً مهنياً أو تعليمات علاج أو توقعاً للمحصول. راجع الإرشاد الزراعي المحلي والقواعد المعمول بها قبل القرارات المهمة أو استخدام أي علاج. يبقى المستخدم مسؤولاً عن قرارات الحقل.",
        "sdg_note": "هذه مجالات إسهام مقصودة وليست اعتماداً رسمياً من الأمم المتحدة أو ادعاءً بأثر مقاس.",
        "offline_detail": "يستخدم التطبيق بيانات عامة مجانية ومكتبات مفتوحة المصدر دون مفاتيح API مدفوعة. يمكن استخدام بيانات الموقع المحفوظة والقيم المدخلة يدوياً دون اتصال. تحتاج الخرائط المباشرة وتحديثات المناخ والتربة والارتفاع إلى الإنترنت. نزّل نموذج المرض مرة قبل الفحص دون اتصال، وحمّل النموذج وبيانات الحقل مسبقاً للإعداد الأولي المنقطع.",
    },
    "zh": {
        "privacy_body": "项目审阅稿。浏览器会请求使用设备位置来定位地图，您可以拒绝。只有运行在线检查时，田地坐标才会发送至 NASA POWER、SoilGrids/ISRIC 和 Open-Meteo；地图请求会发送至 OpenStreetMap。Google 登录会向应用提供身份信息，应用使用生成的账户编号关联保存记录。托管应用中的叶片照片会到达应用服务器进行分析，不会保存到应用数据库。本地 SQLite 数据库存储账户编号、本地密码哈希、检查记录和缓存田地数据。托管部署需要持久且有访问控制的存储。",
        "terms_body": "项目审阅稿。作物范围、伴生种植建议和图像预测仅供一般筛查，不构成专业诊断、治疗说明或产量预测。重要决策和处理措施请先咨询当地农业指导并核实适用规定。田间决策由用户负责。",
        "sdg_note": "这些是预期贡献领域，不代表联合国官方认可或经测量的影响。",
        "offline_detail": "应用使用免费的公共数据和开源库，无需付费 API 密钥。保存的地点数据和手动输入值可离线使用。实时地图、气候、土壤和海拔更新需要互联网。离线筛查前需下载一次病害模型。首次完全离线使用需要预先准备模型和田地数据。",
    },
    "fr": {
        "privacy_body": "Projet de texte à vérifier. Le navigateur demande l’autorisation d’utiliser la position de l’appareil pour centrer la carte; vous pouvez refuser. Les coordonnées du champ sont envoyées à NASA POWER, SoilGrids/ISRIC et Open-Meteo uniquement lors des contrôles en ligne; les tuiles cartographiques viennent d’OpenStreetMap. La connexion Google transmet des informations d’identité à l’application, qui utilise un identifiant de compte généré pour associer l’historique. Une photo de feuille importée dans une application hébergée atteint le serveur pour l’analyse et n’est pas enregistrée dans sa base de données. SQLite stocke les identifiants, les empreintes de mots de passe locaux, les contrôles et les valeurs en cache. Un déploiement hébergé doit utiliser un stockage persistant et contrôlé.",
        "terms_body": "Projet de texte à vérifier. Les plages de culture, suggestions d’association et prédictions d’image sont des outils de dépistage général. Elles ne constituent ni un diagnostic professionnel, ni des instructions de traitement, ni une prévision de rendement. Pour toute décision importante, consultez les services agricoles locaux et vérifiez les règles applicables. L’utilisateur reste responsable des décisions au champ.",
        "sdg_note": "Il s’agit de domaines de contribution visés, et non d’une approbation officielle de l’ONU ni d’un impact mesuré.",
        "offline_detail": "L’application utilise des données publiques gratuites et des bibliothèques libres sans clé API payante. Les données de point enregistrées et les valeurs saisies manuellement fonctionnent hors ligne. Les cartes et l’actualisation du climat, du sol et de l’altitude nécessitent Internet. Téléchargez le modèle de maladie une fois avant le dépistage hors ligne. Une première installation sans réseau exige de précharger le modèle et les données du champ.",
    },
    "ru": {
        "privacy_body": "Черновик для проверки проекта. Браузер запросит разрешение на получение местоположения устройства для карты; вы можете отказать. Координаты поля отправляются в NASA POWER, SoilGrids/ISRIC и Open-Meteo только при онлайн-проверке; запросы карт идут в OpenStreetMap. При входе через Google приложение получает сведения о личности и связывает историю с созданным идентификатором аккаунта. Фото листа, загруженное в размещённое приложение, поступает на сервер для анализа и не сохраняется в базе. SQLite хранит идентификаторы аккаунтов, хеши локальных паролей, сохранённые проверки и кэшированные данные поля. Для хостинга нужны постоянное хранилище и контроль доступа.",
        "terms_body": "Черновик для проверки проекта. Диапазоны культур, советы по совместным посадкам и прогнозы по изображению служат только для предварительной оценки. Это не профессиональный диагноз, не инструкция по лечению и не прогноз урожая. Важные решения и способы обработки проверяйте у местных аграрных специалистов и по действующим правилам. За решения на поле отвечает пользователь.",
        "sdg_note": "Это предполагаемые направления вклада, а не официальное одобрение ООН или измеренная оценка воздействия.",
        "offline_detail": "Приложение использует бесплатные открытые данные и библиотеки без платных API-ключей. Сохранённые данные точки и введённые вручную значения доступны офлайн. Для обновления карт, климата, почвы и высоты нужен интернет. Перед офлайн-проверкой один раз загрузите модель болезни. Для первой установки без сети заранее загрузите модель и данные поля.",
    },
    "es": {
        "privacy_body": "Borrador para revisión del proyecto. El navegador solicita permiso para usar la ubicación del dispositivo en el mapa; puedes denegarlo. Las coordenadas del campo se envían a NASA POWER, SoilGrids/ISRIC y Open-Meteo solo al realizar análisis en línea; las solicitudes de mapas van a OpenStreetMap. El inicio con Google comparte datos de identidad con la aplicación, que usa un identificador de cuenta generado para vincular el historial. Una foto subida a una aplicación alojada llega al servidor para su análisis y no se guarda en la base de datos. SQLite guarda identificadores de cuenta, hashes de contraseñas locales, revisiones y datos de campo en caché. El alojamiento requiere almacenamiento persistente y control de acceso.",
        "terms_body": "Borrador para revisión del proyecto. Los rangos de cultivo, las sugerencias de asociación y las predicciones de imágenes son herramientas de detección general. No son un diagnóstico profesional, instrucciones de tratamiento ni pronósticos de rendimiento. Consulta asesoría agrícola local y las normas aplicables antes de decisiones importantes o tratamientos. El usuario es responsable de las decisiones en el campo.",
        "sdg_note": "Estas son áreas de contribución previstas, no un respaldo oficial de la ONU ni una afirmación de impacto medido.",
        "offline_detail": "La aplicación usa datos públicos gratuitos y bibliotecas de código abierto sin claves API de pago. Los datos guardados del lugar y los valores manuales se pueden usar sin conexión. Los mapas y las actualizaciones de clima, suelo y elevación requieren internet. Descarga el modelo de enfermedades una vez antes de usarlo sin conexión. La instalación inicial desconectada requiere precargar el modelo y los datos del campo.",
    },
}


def t(key: str, language: str = "en") -> str:
    """Return a translated interface string, falling back to English."""
    code = language if language in TEXT else "en"
    return TEXT[code].get(key, EXTRA_TEXT[code].get(key, TEXT["en"].get(key, EXTRA_TEXT["en"].get(key, key))))
